---  

- hosts: all
  become: true
  tasks:
  - name: install update (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 


     
  - name: install apache2 package
    apt: 
      name: 
        - apache2
        
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 
 
       

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
        
